
platform :ios, '8.0'
use_frameworks!

target 'MACTableViewSwift' do
inhibit_all_warnings!
pod 'MBProgressHUD', '~> 0.9.1'
# 下拉刷新
pod 'MJRefresh', '~> 3.1.0'
# empty scrollView
pod 'DZNEmptyDataSet', '~> 1.7.2'
end
